package me.lemon.winter.util;

import java.util.HashMap;
import java.util.Map;

public class KeyHelper {
    private static String wow = "THIS IS SO STUPID!!!!!! THERE HAS GOT TO BE A BETTER WAY TO DO THIS!";
    private static final Map<Integer, String> KEY_MAP = new HashMap();

    public KeyHelper() {
    }

    public static String getKeyName(int keycode) {
        return keycode == -1 ? "NONE" : (String)KEY_MAP.get(keycode);
    }

    static {
        KEY_MAP.put(193, "Abnt C1");
        KEY_MAP.put(194, "Abnt C2");
        KEY_MAP.put(107, "Numpad +");
        KEY_MAP.put(246, "Attn");
        KEY_MAP.put(8, "Backspace");
        KEY_MAP.put(3, "Break");
        KEY_MAP.put(12, "Clear");
        KEY_MAP.put(247, "Cr Sel");
        KEY_MAP.put(110, "Numpad .");
        KEY_MAP.put(111, "Numpad /");
        KEY_MAP.put(249, "Er Eof");
        KEY_MAP.put(27, "Esc");
        KEY_MAP.put(43, "Execute");
        KEY_MAP.put(248, "Ex Sel");
        KEY_MAP.put(230, "IcoClr");
        KEY_MAP.put(227, "IcoHlp");
        KEY_MAP.put(48, "0");
        KEY_MAP.put(49, "1");
        KEY_MAP.put(50, "2");
        KEY_MAP.put(51, "3");
        KEY_MAP.put(52, "4");
        KEY_MAP.put(53, "5");
        KEY_MAP.put(54, "6");
        KEY_MAP.put(55, "7");
        KEY_MAP.put(56, "8");
        KEY_MAP.put(57, "9");
        KEY_MAP.put(65, "A");
        KEY_MAP.put(66, "B");
        KEY_MAP.put(67, "C");
        KEY_MAP.put(68, "D");
        KEY_MAP.put(69, "E");
        KEY_MAP.put(70, "F");
        KEY_MAP.put(71, "G");
        KEY_MAP.put(72, "H");
        KEY_MAP.put(73, "I");
        KEY_MAP.put(74, "J");
        KEY_MAP.put(75, "K");
        KEY_MAP.put(76, "L");
        KEY_MAP.put(77, "M");
        KEY_MAP.put(78, "N");
        KEY_MAP.put(79, "O");
        KEY_MAP.put(80, "P");
        KEY_MAP.put(81, "Q");
        KEY_MAP.put(82, "R");
        KEY_MAP.put(83, "S");
        KEY_MAP.put(84, "T");
        KEY_MAP.put(85, "U");
        KEY_MAP.put(86, "V");
        KEY_MAP.put(87, "W");
        KEY_MAP.put(88, "X");
        KEY_MAP.put(89, "Y");
        KEY_MAP.put(90, "Z");
        KEY_MAP.put(106, "Numpad *");
        KEY_MAP.put(252, "NoName");
        KEY_MAP.put(96, "Numpad 0");
        KEY_MAP.put(97, "Numpad 1");
        KEY_MAP.put(98, "Numpad 2");
        KEY_MAP.put(99, "Numpad 3");
        KEY_MAP.put(100, "Numpad 4");
        KEY_MAP.put(101, "Numpad 5");
        KEY_MAP.put(102, "Numpad 6");
        KEY_MAP.put(103, "Numpad 7");
        KEY_MAP.put(104, "Numpad 8");
        KEY_MAP.put(105, "Numpad 9");
        KEY_MAP.put(186, ":");
        KEY_MAP.put(226, ">");
        KEY_MAP.put(191, "?");
        KEY_MAP.put(192, "~");
        KEY_MAP.put(219, "[");
        KEY_MAP.put(220, "\\");
        KEY_MAP.put(221, "]");
        KEY_MAP.put(222, "\"");
        KEY_MAP.put(223, "!");
        KEY_MAP.put(240, "Oem Attn");
        KEY_MAP.put(243, "Auto");
        KEY_MAP.put(225, "Ax");
        KEY_MAP.put(245, "Back Tab");
        KEY_MAP.put(254, "OemClr");
        KEY_MAP.put(188, "<");
        KEY_MAP.put(242, "Copy");
        KEY_MAP.put(239, "Cu Sel");
        KEY_MAP.put(244, "Enlw");
        KEY_MAP.put(241, "Finish");
        KEY_MAP.put(149, "Loya");
        KEY_MAP.put(147, "Mashu");
        KEY_MAP.put(150, "Roya");
        KEY_MAP.put(148, "Touroku");
        KEY_MAP.put(234, "Jump");
        KEY_MAP.put(189, "-");
        KEY_MAP.put(235, "OemPa1");
        KEY_MAP.put(236, "OemPa2");
        KEY_MAP.put(237, "OemPa3");
        KEY_MAP.put(190, ".");
        KEY_MAP.put(187, "+");
        KEY_MAP.put(233, "Reset");
        KEY_MAP.put(238, "WsCtrl");
        KEY_MAP.put(253, "Pa1");
        KEY_MAP.put(231, "Packet");
        KEY_MAP.put(250, "Play");
        KEY_MAP.put(229, "Process");
        KEY_MAP.put(13, "Enter");
        KEY_MAP.put(41, "Select");
        KEY_MAP.put(108, "Separator");
        KEY_MAP.put(32, "Space");
        KEY_MAP.put(109, "Num -");
        KEY_MAP.put(9, "Tab");
        KEY_MAP.put(251, "Zoom");
        KEY_MAP.put(255, "no VK mapping");
        KEY_MAP.put(30, "Accept");
        KEY_MAP.put(93, "Context Menu");
        KEY_MAP.put(166, "Browser Back");
        KEY_MAP.put(171, "Browser Favorites");
        KEY_MAP.put(167, "Browser Forward");
        KEY_MAP.put(172, "Browser Home");
        KEY_MAP.put(168, "Browser Refresh");
        KEY_MAP.put(170, "Browser Search");
        KEY_MAP.put(169, "Browser Stop");
        KEY_MAP.put(20, "Caps Lock");
        KEY_MAP.put(28, "Convert");
        KEY_MAP.put(46, "Delete");
        KEY_MAP.put(40, "Arrow Down");
        KEY_MAP.put(35, "End");
        KEY_MAP.put(112, "F1");
        KEY_MAP.put(121, "F10");
        KEY_MAP.put(122, "F11");
        KEY_MAP.put(123, "F12");
        KEY_MAP.put(124, "F13");
        KEY_MAP.put(125, "F14");
        KEY_MAP.put(126, "F15");
        KEY_MAP.put(127, "F16");
        KEY_MAP.put(128, "F17");
        KEY_MAP.put(129, "F18");
        KEY_MAP.put(130, "F19");
        KEY_MAP.put(113, "F2");
        KEY_MAP.put(131, "F20");
        KEY_MAP.put(132, "F21");
        KEY_MAP.put(133, "F22");
        KEY_MAP.put(134, "F23");
        KEY_MAP.put(135, "F24");
        KEY_MAP.put(114, "F3");
        KEY_MAP.put(115, "F4");
        KEY_MAP.put(116, "F5");
        KEY_MAP.put(117, "F6");
        KEY_MAP.put(118, "F7");
        KEY_MAP.put(119, "F8");
        KEY_MAP.put(120, "F9");
        KEY_MAP.put(24, "Final");
        KEY_MAP.put(47, "Help");
        KEY_MAP.put(36, "Home");
        KEY_MAP.put(228, "Ico00 *");
        KEY_MAP.put(45, "Insert");
        KEY_MAP.put(23, "Junja");
        KEY_MAP.put(21, "Kana");
        KEY_MAP.put(25, "Kanji");
        KEY_MAP.put(182, "App1");
        KEY_MAP.put(183, "App2");
        KEY_MAP.put(180, "Mail");
        KEY_MAP.put(181, "Media");
        KEY_MAP.put(1, "Left Button **");
        KEY_MAP.put(162, "Left Ctrl");
        KEY_MAP.put(37, "Arrow Left");
        KEY_MAP.put(164, "Left Alt");
        KEY_MAP.put(160, "Left Shift");
        KEY_MAP.put(91, "Left Win");
        KEY_MAP.put(4, "Middle Button **");
        KEY_MAP.put(176, "Next Track");
        KEY_MAP.put(179, "Play / Pause");
        KEY_MAP.put(177, "Previous Track");
        KEY_MAP.put(178, "Stop");
        KEY_MAP.put(31, "Mode Change");
        KEY_MAP.put(34, "Page Down");
        KEY_MAP.put(29, "Non Convert");
        KEY_MAP.put(144, "Num Lock");
        KEY_MAP.put(146, "Jisho");
        KEY_MAP.put(19, "Pause");
        KEY_MAP.put(42, "Print");
        KEY_MAP.put(33, "Page Up");
        KEY_MAP.put(2, "Right Button **");
        KEY_MAP.put(163, "Right Ctrl");
        KEY_MAP.put(39, "Arrow Right");
        KEY_MAP.put(165, "Right Alt");
        KEY_MAP.put(161, "Right Shift");
        KEY_MAP.put(92, "Right Win");
        KEY_MAP.put(145, "Scrol Lock");
        KEY_MAP.put(95, "Sleep");
        KEY_MAP.put(44, "Print Screen");
        KEY_MAP.put(38, "Arrow Up");
        KEY_MAP.put(174, "Volume Down");
        KEY_MAP.put(173, "Volume Mute");
        KEY_MAP.put(175, "Volume Up");
        KEY_MAP.put(5, "X Button 1 **");
        KEY_MAP.put(6, "X Button 2 **");
    }
}
